### ISSUE TITLE
Bug: duplicated choices in reporting/partner select

### ISSUE THREAD

**Issue by paulgirard** [medialab/ricardo#102]
![image](https://user-images.githubusercontent.com/193478/92217225-b60d0380-ee97-11ea-8138-69fd58f604c1.png)

**Comment by sim51** [comment]
The issue comes from the API response. 
For `Aden`, the API returns two lines, one with the GPH_CODE, and an other one with the value NULL.

The SQL query that is generated by the API is the following : `SELECT DISTINCT reporting_slug, reporting_GPH_code FROM flow_joined`.

@paulgirard thinks that the problem comes the script that generates the DB.

**Comment by paulgirard** [comment]
I corrected this in https://github.com/medialab/ricardo_data/commit/c3a7b446cd58f056c18ba80b136aad009f8e3772
