### ISSUE TITLE
Permalinks

### ISSUE THREAD

**Issue by paulgirard** [medialab/ricardo#73]
Add permalink feature to views as follow : 
- [x] country : /country/country_slug?
- [x] bilateral : /bilateral/countrySlug1|countrySlug2
- [x] metadata: /metadata/flowsType?

if one param is missing use/update [configuration defaults](https://github.com/medialab/ricardo/blob/master/client/js/config.sample.js#L5-L7). 

We chose not to include lang in the permalink. The existing language detection mechanism + local storage will suffice.

**Comment by sim51** [comment]
I implemented the permanent url for the route, there is no query params so far.

Moreover, for the bilateral the algo is the following : 

* `/bilateral` redirect to bilatreal with the source entity store in localstorage orthe default one. The target entity is the first partner.
* `/bilateral/France` redirect to bilatreal with the source entity `France` and the target entity is the first partner.
* `/bilateral/France/test` Because `test` is not a valid entity it redirects  to `/bilateral/France`
* `/bilateral/test/France` Because `test` is not a valid entity it redirects  to `/bilateral/Alaska/France`  where Alaska is in the localStorage or is the default

**Comment by sim51** [comment]
Since  commit 19df592bc5f5c878fcb40c8cbb1e89d94b3e299c query params are implemented. 
There is only one attribute that is not sync with the url, it's Find Reporting` on  `metadata page`.
