### ISSUE TITLE
PARTNER page

### ISSUE THREAD

**Issue by paulgirard** [medialab/ricardo#78]
- [x] Rename country page as Reporting

create a new page partner.
This illustration shows the page structure. We reused the reporting list from the metadata fro illustration only.
The number of reporting barchart and the reporting data presence lines should take the complete width to keep it synced with political status and detailed curves.

![image](https://user-images.githubusercontent.com/193478/87289895-8bd54000-c4fd-11ea-8d1b-88a5e6f968d0.png)

An other (better ?) possibility is to reuse the concept of number of reporting from world view and the partner histogram from country. We would transform barchart by balance to a simple yes/no data blocks or lines.
![image](https://user-images.githubusercontent.com/193478/87292435-17040500-c501-11ea-91d5-46298a9de1df.png)

- [x] same political status component as the one developed for reporting #75 
- [x] the number of reporting by year which cites this partner
- [ ] list of those reportings with an indication of for each year the partner has been cited (only the presence of data no quantity)
- [x] reporting trade comparator (allow to select up to 5 reporting) (same component as une country view)

**Comment by jacomyal** [comment]
Should the old country page route remain `#!/country/:reportingId`, or should it become `#!/reporting/:reportingId` (but introduce a breaking change) ? Or should we just add a redirection ?

Since this is easy to to, I'll leave routing as is for now.

**Comment by jacomyal** [comment]
UPDATE: I moved the route, and I added the redirection.

**Comment by jacomyal** [comment]
So, I did some things on this issue but I can't finish it before leaving for holidays.

Here's where it's at:

- [x] The controller and partial have been created
- [x] The title form (with partner and date boundaries selection) has been implemented
- [x] The partner and date boundaries are bound to the permalinks
- [x] The list of available partners and the flows are bound to the good API endpoints

What remains to do:
- [ ] Inspect flows data, because I suspect they are not well shaped (payload oftens exceeds 1mb)
- [ ] The number of reporting by year which cites this partner
- [ ] The citation curves of those reportings
- [ ] Reportings trade comparator

**Comment by sim51** [comment]
- [ ] Remove the percent feature on the world trade comparison
- [ ] Add the raw table feature for the partner flows
